moai:
    initialized: true
    initialized_at: "2025-12-19T00:00:00Z"
    version: 2.2.2
project:
    created_at: ""
    description: ""
    mode: personal
    name: ""
    optimized: false
    template_version: 2.2.2
